### ISSUE TITLE
ДЗ 4

### ISSUE THREAD

**Issue by skubik** [MIEE-ACS/domashnee-zadanie-no4-skubik#1]
Здравствуйте! Задание выполнено. Мой вариант №13.

**Comment by d-makarenko** [comment]
Задание было такое:

    количество элементов массива, лежащих в диапазоне от А до В;

Имелось в виду, что нужно посчитать какое количество элементов в массиве имеет значение находящееся в диапазоне [A; B].

А в решении:
```c#
                    if (a > b)
                    {
                        for (i = b; i < a - 1; i++)
                            k++;
                    }
                    if (b > a)
                    {
                        for (i = a; i < b - 1; i++)
                            k++;
                    }
```

А это просто  `|A - B|` записаное в особо извращенной форме 😀

Второе задание было сложное и решено правильно, и все хорошо оформлено.
4-/4
